# 安装proxysql并初始化

- name: Copy the installation package,mysql source and logrotate script
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  with_items:
    - { src: "{{ proxysql_package }}", dest: "{{ package_dir }}" }
    - { src: 'proxysql', dest: '/etc/logrotate.d/proxysql' }
    - { src: 'mysql80-community-release-el7-3.noarch.rpm', dest: "{{ package_dir }}" }

- name: Install mysql resource
  yum:
    name: "{{ package_dir }}/mysql80-community-release-el7-3.noarch.rpm"
    state: present

- name: Install mysql client
  yum:
    name: [mysql-community-common.x86_64, mysql-community-libs.x86_64, mysql-community-client.x86_64]
    state: present
  register: result
  retries: 3
  until: result is succeeded

- name: Rendering mysql_config_editor.sh
  template:
    src: mysql_config_editor.sh.j2
    dest: "{{ package_dir }}/mysql_config_editor.sh"
    owner: root
    group: root
    mode: 0774

- name: Case sensitive password string match for logining proxysql
  shell: "/usr/bin/expect {{ package_dir }}/mysql_config_editor.sh"
  run_once: true

- name: Remove mysql_config_editor.sh
  file:
    path: "{{ package_dir }}/mysql_config_editor.sh"
    state: absent

#- name: Case sensitive password string match for logining proxysql
#  expect:
#    command: mysql_config_editor set --login-path=proxysql --host=127.0.0.1 -P 6032 --user=admin --password
#    responses:
#      Question:
#        - (?i)password: "{{ admin_login_password }}"
#        - (?i)Continue: y
#  no_log: True

- name: Add the job of logrotate for proxysql
  cron:
    name: "logrotate"
    minute: "55"
    hour: "23"
    job: "/usr/sbin/logrotate -vf -s /var/lib/logrotate/logrotate.status /etc/logrotate.d/proxysql > /dev/null"

- name: Install ProxySQL
  yum:
    name: "{{ package_dir }}/{{ proxysql_package }}"
    state: present

- name: Rendering proxysql profile
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: proxysql
    group: proxysql
  with_items:
    - { src: 'proxysql.cnf.j2', dest: '/etc/proxysql.cnf' }

- name: Enable proxysql server
  systemd:
    name: proxysql
    enabled: yes

- name: Start proxysql
  systemd:
    name: proxysql
    state: started

- name: Rendering auto_adjust_mysql_query_rules.sh
  template:
    src: auto_adjust_mysql_query_rules.sh.j2
    dest: /var/lib/proxysql/auto_adjust_mysql_query_rules.sh
    owner: proxysql
    group: proxysql
    mode: 0774

- name: Wait for ProxySQL is running
  pause: seconds=3

- name: Modify admin password
  proxysql_global_variables:
    login_user: 'admin'
    login_password: 'admin'
    variable: "{{ item.variable }}"
    value: "{{ item.value }}"
    load_to_runtime: True
    save_to_disk: True
  with_items:
    - { variable: 'admin-admin_credentials', value: "admin:{{ admin_login_password }}" }
    
- name: Modify mysql-monitor password
  proxysql_global_variables:
    login_user: 'admin'
    login_password: "{{ admin_login_password }}"
    variable: "{{ item.variable }}"
    value: "{{ item.value }}"
    load_to_runtime: True
    save_to_disk: True
  with_items:
    - { variable: 'mysql-monitor_password', value: "{{ mysql_monitor_password }}" }

- name: Add mysql_users
  proxysql_mysql_users:
    login_user: 'admin'
    login_password: "{{ admin_login_password }}"
    username: "{{ item.username }}"
    password: "{{ item.password }}"
    default_hostgroup: 10
    transaction_persistent: yes
    max_connections: 10000
    state: present
    load_to_runtime: yes
    save_to_disk: yes
  with_items:
    - { username: 'root', password: "{{ root_password }}" }
    - { username: "{{ business_user }}", password: "{{ business_password }}" }
    - { username: 'audit', password: "{{ mysql_monitor_password }}" }

- name: Encrypt mysql_users
  proxysql_manage_config:
    login_user: 'admin'
    login_password: "{{ admin_login_password }}"
    action: "SAVE"
    config_settings: "MYSQL USERS"
    direction: "FROM"
    config_layer: "RUNTIME"
  tags: manage_user

- name: Add proxysql scheduler
  proxysql_scheduler:
    login_user: 'admin'
    login_password: "{{ admin_login_password }}"
    active: 1
    interval_ms: 3000
    filename: /var/lib/proxysql/auto_adjust_mysql_query_rules.sh
    arg1: "{{ admin_login_password }}"
    state: present
    load_to_runtime: True
    save_to_disk: True