# 安装proxysql并初始化

- name: Copy the installation package,mysql source and logrotate script
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  with_items:
    - { src: "{{ proxysql_package }}", dest: "{{ package_dir }}" }
    - { src: 'proxysql', dest: '/etc/logrotate.d/proxysql' }
    - { src: 'mysql80-community-release-el7-3.noarch.rpm', dest: "{{ package_dir }}" }

- name: Install mysql resource
  yum:
    name: "{{ package_dir }}/mysql80-community-release-el7-3.noarch.rpm"
    state: present

- name: Install mysql client
  yum:
    name: [mysql-community-common.x86_64, mysql-community-libs.x86_64, mysql-community-client.x86_64]
    state: present
  register: result
  retries: 3
  until: result is succeeded

- name: Rendering mysql_config_editor.sh
  template:
    src: mysql_config_editor.sh.j2
    dest: "{{ package_dir }}/mysql_config_editor.sh"
    owner: root
    group: root
    mode: 0774

- name: Rendering auto_adjust_mysql_query_rules.sh
  template:
    src: auto_adjust_mysql_query_rules.sh.j2
    dest: /var/lib/proxysql/auto_adjust_mysql_query_rules.sh
    owner: proxysql
    group: proxysql
    mode: 0774

- name: Case sensitive password string match for logining proxysql
  shell: "/usr/bin/expect {{ package_dir }}/mysql_config_editor.sh"

- name: Remove mysql_config_editor.sh
  file:
    path: "{{ package_dir }}/mysql_config_editor.sh"
    state: absent

#- name: Case sensitive password string match for logining proxysql
#  expect:
#    command: mysql_config_editor set --login-path=proxysql --host=127.0.0.1 -P 6032 --user=admin --password
#    responses:
#      Question:
#        - (?i)password: "{{ admin_login_password }}"
#        - (?i)Continue: y
#  no_log: True

- name: Add the job of logrotate for proxysql
  cron:
    name: "logrotate"
    minute: "55"
    hour: "23"
    job: "/usr/sbin/logrotate -vf -s /var/lib/logrotate/logrotate.status /etc/logrotate.d/proxysql > /dev/null"

- name: Rendering profile and proxysql_initial_user.sql
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: proxysql
    group: proxysql
  with_items:
    - { src: 'proxysql.cnf.j2', dest: '/etc/proxysql.cnf' }
    - { src: 'proxysql_initial_user.sql.j2', dest: "{{ package_dir }}/proxysql_initial_user.sql" }

- name: Install ProxySQL
  yum:
    name: "{{ package_dir }}/{{ proxysql_package }}"
    state: present

- name: Start proxysql
  systemd:
    name: proxysql
    state: started

- name: Wait for ProxySQL is running
  pause: seconds=3

- name: Initial proxysql users and scheduler
  shell: "mysql -uadmin -p'admin' -h 127.0.0.1 -P{{ admin_login_port }} --prompt='Admin> ' --default-auth=mysql_native_password < {{ package_dir }}/proxysql_initial_user_scheduler.sql"

- name: Remove proxysql_initial_user_scheduler.sql
  file:
    path: "{{ package_dir }}/proxysql_initial_user_scheduler.sql"
    state: absent