---
# tasks file for proxysql_ray
- include: password.yml
  when: not is_upgrade | default(False)

- include: system_check.yml
  when: not is_upgrade | default(False)

- include: prepare.yml

- include: install.yml

- include: install_tools
  when: percona_tools

- include: upgrade.yml
  when: is_upgrade | default(False)