---
# tasks file for proxysql_ray
- include: password.yml
  when: proxysql | default(False)

- include: system_check.yml
  when: proxysql | default(False)

- include: install.yml
  when: proxysql | default(False)

- include: install_tools.yml
  when: pmm_client | default(False)

- include: upgrade.yml
  when: is_upgrade | default(False)