---
# tasks file for proxysql_ray
- include: password.yml

- include: system_check.yml

- include: prepare.yml

- include: install.yml

- include: install_tools
  when: percona_tools

- include: upgrade.yml
  when: is_upgrade | default(False)