---
# tasks file for proxysql_ray
- include: password.yml

- include: system_check.yml

- include: prepare.yml

- include: install.yml
  when: proxysql_group_replication_hostgroups

- include: install_traditional_replication.yml
  when: proxysql_replication_hostgroups