- name: Copy the installation package,mysql source and password-free login script
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  with_items:
    - { src: "{{ proxysql_package }}", dest: "{{ package_dir }}" }
    - { src: 'proxysql', dest: '/etc/logrotate.d/proxysql' }
    - { src: 'mysql80-community-release-el7-3.noarch.rpm', dest: "{{ package_dir }}" }

- name: Install mysql resource
  yum:
    name: "{{ package_dir }}/mysql80-community-release-el7-3.noarch.rpm"
    state: present

- name: Install mysql client
  yum:
    name: [mysql-community-common.x86_64,mysql-community-libs.x86_64,mysql-community-client.x86_64]
    state: present
  register: result
  retries: 3
  until: result is succeeded

- name: Rendering mysql_config_editor.sh
  template:
    src: mysql_config_editor.sh.j2
    dest: "{{ package_dir }}/mysql_config_editor.sh"
    owner: root
    group: root
    mode: 0774

#- name: Implement log rotation
# shell: "/usr/bin/expect {{ package_dir }}/mysql_config_editor.sh"
  
- name: Case sensitive password string match for logining proxysql
  expect:
    command: mysql_config_editor set --login-path=proxysql --host=127.0.0.1 -P 6032 --user=admin --password
    responses:
      Question:
        - (?i)password: "{{ admin_login_password }}"
        - (?i)Continue: y
  no_log: true

- name: Add the job of logrotate for proxysql
  cron:
    name: "logrotate"
    minute: "55"
    hour: "23"
    job: "/usr/sbin/logrotate -vf -s /var/lib/logrotate/logrotate.status /etc/logrotate.d/proxysql > /dev/null"
