# 系统环境检测，排除干扰

- name: 关闭firewalld
  service: name=firewalld state=stopped enabled=no

- name: 永久关闭selinux
  lineinfile:
    dest: /etc/selinux/config
    regexp: "^SELINUX="
    line: "SELINUX=disabled"

- name: 卸载系统自带的mariadb
  yum:
    name: mariadb
    state: absent

- name: 备份原proxysql的db文件
  copy:
    src: "{{ db_file }}"
    dest: "{{ package_dir }}"
    remote_src: yes
    owner: proxysql
    group: proxysql
    mode: '0644'
    backup: yes
  when: is_update

- name: 卸载原版本proxysql
  yum:
    name: proxysql
    state: absent
  when: is_update

- name: 安装基础软件包
  yum:
    name: "{{ packages }}"
    state: latest

#- name: 更新所有软件包
#  yum:
#    name: '*'
#    state: latest
