# 系统环境检测，排除干扰

- name: 关闭firewalld
  service: name=firewalld state=stopped enabled=no

- name: 永久关闭selinux
  lineinfile:
    dest: /etc/selinux/config
    regexp: "^SELINUX="
    line: "SELINUX=disabled"

- name: Proxysql status
  systemd:
    name: proxysql
    state: started
  register: result
  when: whether_uninstall

- name: Stop proxysql server
  systemd:
    name: proxysql
    state: stopped
  when: whether_uninstall and result is succeeded

- name: 备份原proxysql的db文件
  copy:
    src: "{{ db_file }}"
    dest: "{{ package_dir }}"
    remote_src: yes
    owner: proxysql
    group: proxysql
    mode: '0644'
    backup: no
  when: whether_uninstall

- name: 卸载系统自带的mariadb和已经安装的proxysql
  yum:
    name: [mariadb, proxysql]
    state: absent
  when: whether_uninstall

- name: Remove proxysql directory
  file:
    path: "{{ datadir }}"
    state: absent
  when: whether_uninstall

- name: 安装基础软件包
  yum:
    name: "{{ packages }}"
    state: latest

#- name: Upgrade pip
#  pip:
#    name: pip
#    state: latest

- name: Install pexpect
  pip:
    name: pexpect
    state: latest
#- name: 更新所有软件包
#  yum:
#    name: '*'
#    state: latest