- name: Copy the latest ProxySQL
  copy:
    src: "{{ proxysql_upgrade_package }}"
    dest: "{{ package_dir }}"

- name: Stop keepalived
  systemd:
    name: keepalived
    state: stopped

- name: 停止proxysql服务
  systemd:
    name: proxysql
    state: stopped

- name: 备份原proxysql的db文件
  copy:
    src: "{{ item }}"
    dest: "{{ package_dir }}"
    remote_src: yes
    owner: proxysql
    group: proxysql
    mode: '0644'
    backup: no
  with_items:
    - "{{ db_file }}"
    - "{{ db_stats_file }}"

- name: 卸载原版本proxysql
  yum:
    name: proxysql
    state: absent

- name: Install the latest ProxySQL
  yum:
    name: "{{ package_dir }}/{{ proxysql_upgrade_package }}"
    state: present
  notify:
    - Start ProxySQL
    - Start keepalived

- name: Rename proxysql.rpmsave file to proxysql
  copy:
    src: /etc/logrotate.d/proxysql.rpmsave
    dest: /etc/logrotate.d/proxysql
    remote_src: yes
    owner: root
    group: root
    mode: '0644'