---
# handlers file for proxysql_ray
- name: Stop keepalived
  systemd:
    name: keepalived
    state: stopped

- name: Start keepalived
  systemd:
    name: keepalived
    state: started

- name: Start ProxySQL
  systemd:
    name: proxysql
    state: started

- name: Reload systemd
  systemd:
    daemon_reload: yes

- name: Wait for ProxySQL is running
  pause: seconds=3