- name: Add mysql server
  proxysql_backend_servers:
    login_user: 'admin'
    login_password: "{{ admin_login_password }}"
    hostgroup_id: 10
    hostname: "{{ dbserver }}"
    port: "{{ mysql_port }}"
    compression: 1
    max_connections: "{{ max_connections }}"
    state: present
    load_to_runtime: True
    save_to_disk: True

- name: Delete mysql old server
  proxysql_backend_servers:
    login_user: 'admin'
    login_password: "{{ admin_login_password }}"
    hostgroup_id: 10
    hostname: "{{ olddbserver }}"
    port: "{{ mysql_port }}"
    compression: 1
    max_connections: "{{ max_connections }}"
    state: absent
    load_to_runtime: True
    save_to_disk: True


