- name: Modify query rule2
  proxysql_query_rules:
    login_user: 'admin'
    login_password: "{{ admin_login_password }}"
    rule_id: 3
    active: 1
    match_digest: '^select.*from'
    destination_hostgroup: 30
    cache_ttl: "{{ cache_ttl }}"
    apply: 1
    state: present
    load_to_runtime: True
    save_to_disk: True

